services:
  vehicle:
    build: .
    container_name: vehicle
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true

    volumes:
      - /dev:/dev

    environment:
      - MAVLINK_URL=tcp:127.0.0.1:5777